### PR TITLE
PopulateDropdowns

### PR DESCRIPTION
**Pull request by Camtendo**
Populates the dropdowns on the admin page on page load.

Closes https://github.com/The-Velvet-Room/web-overlay/issues/122

### CODE REVIEW

**Comment by nswartz** [comment]
This is slightly unrelated, but on the subject of dropdowns, there appears to be a few where selecting 'none' is not a valid option.

**Comment by Camtendo** [comment]
I just tested the `None` options and they all work on this branch, so I dunno.

**Comment by nswartz** [comment]
I went to Derek's site and choosing a port, then attempting to select 'None' again does not remove the port color from around the name.

**Comment by Camtendo** [comment]
Ohhh, I misunderstood. I'll see if I can fix that while I'm in here.

**Comment by Camtendo** [comment]
It seems that's an implementation issue. That's worth making a different ticket for. You want to do the honors?

**Comment by dguenther** [comment]
Could this be done when the list is built, instead of after?

**Comment by Camtendo** [comment]
Dat efficiency. Yeah, gimme a sec.

**Comment by Camtendo** [comment]
Actually, we have to do it this way. The data isn't received when the lists are constructed.

**Comment by dguenther** [comment]
Hmm, would it hurt to delay list construction until the data is received? Or at least disable them so they don't snap to their correct state

**Comment by Camtendo** [comment]
That's a good idea actually. I'll commit or post back with results.

**Pull request merged**
